# MySQL 데이터베이스 연결 정보
[mysql]
host = "43.202.226.147"
user = "ku.do"
passwd = "LXsYicuMd6"
db = "boosters"
port = 3306
charset = "utf8"

# Google Sheets API 및 스프레드시트 정보
[google_sheets]
type = "service_account"
project_id = "python-spreadsheet-409212"
private_key_id = "3df25e0dc16635db9cc0c805c1e4e59fc4dd84e2"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeD1ohlfVv5jdA\nXjcsVMh0rOS9AY5BBQA96VDwkl3pcFWXsMtrNZKr5GJ/t5QqcNZDvMg+5GEamtXY\nCSRf5YTx9qHU3v10Z9TKdoeF00CD+lSJO91Ekh+EGgPnM4WyZXGA3D6Z5pUqA6Gs\nQwpWKL9zFoXx/7FLSxZY1VsI1+3w1ESQph/ujmE+7qN2ZNypQUzSSTPoA0+0NS3b\n5if20vf9Kc2+avS5fsq+AMC2sUZmVsWxvMJMfr+GWds8A9PBQ1UaSdyBwlpD1+e/\nI/9H5L8O1ihBXALTo3cZ8fObEPIIGObOqQ6Spw+efUvJqm+2y84c7SQUL0O/GhDZ\n/WbQXa9XAgMBAAECggEAZTc6LfTcWpTkukI3g81hUU09Nalv3dMZuR6P9hfBFpZN\nbUb4cXWJ1S/UdcKHlpC4GUgDPid621WYA1Cnc856Oo/gU9cQT+7D30UHoMgZsA56\nWdMfmBHCq8Pv44Joflge1E2PezbO5seg+ZPVMlCAc0Tg6N1TQq6HERau1+kUW6CL\nzyCpqpRCHRq49zpePqf03jVD2tia7WungujeFNZLMMrqHgk74qfcc6W3tBAuRbJO\nSwkSI3PTDXX/h3aHSzDmeZNvdFWOhQDPRttGtfyZEZQrPbU8CESHs7s1fEVZNzcg\nQ8BzqZn72fHNGnUKpFJ12MEc05HnqDnnBsAUsuF1gQKBgQD5LhJPX+c4l/jwvZBi\nja/Ed6DtQONXyX1LfkYxD1GofbQTGb+LKlkKSVmLtRCu9JzyCmiKvYarqW2cvOGy\nXA5bAuL9RqySDJKyhIhUg51xS6MI98ost5bMqnSWIG01XKd5Cg+vTUtSkSxsJtjH\nHByUplEl1fSwAD7c4L8sybL51QKBgQDkI0JKfwoMqxm1T36YDyy4bgqSenRiROLC\nkQp/ODr39KTN5nUqYgDf5O876mMBYumCgJk2N5LUF4gsazMBtM1wMpp8/MpXsDbp\nMxz9k0yFuPCCi4UAOe+76nW+ocM6KZbMSVLUa8WMESzjXso15J25KVog5Naoo0g3\n8cccG94OewKBgQDnGNh4bxx1u1RwiY7YKEnkb4J7p5txdnhSxLj6lReJqZORx2aC\n/fJ4fNCkpnfjmw/X1tlgGyhEGq2DGRZFIeVaeRHmDl7MUQbYs9vwbeReB+Ub0xvZ\nXydnh4r7FPXT8KuNsUwcrBX4bJWDdH/GIgdLwfgunAEEHiYvGe2T7zijRQKBgQCG\nhngPn6vYXohxTqfymHghZNodF9JLJB2m54oODKVRE1SfCXcrf9DONZwQc5zf82iI\niLZPryOIpzuoHapdJjVCJMTOUO4sGP+4MWi16kbkT3KbOBQ8Vu2TnKTDvXV2dZGz\ncsVB9y7s8i/K/1kzwFR1G/pGjUo69NWgD5T+cTxWwwKBgEaycHW0dSTcjmpfCn//\njN6vxp+nQiQYdzh9Ee1VQOLb+ZPoDenSc9kGrebH7B4PuQL2PLzZ+zKJaiWy82Oe\nUXRlBhS43WIAVj/OKniTjVUmU6+03dlBCpSBvdH6srufZQCP/52Pcmnh9gzZOV7V\nVEQdu+fo9UtBVXlVyJ0rouXS\n-----END PRIVATE KEY-----\n"
client_email = "boosters-chyoo@python-spreadsheet-409212.iam.gserviceaccount.com"
client_id = "117052948883792624597"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/boosters-chyoo%40python-spreadsheet-409212.iam.gserviceaccount.com"
# 🚨 공유받은 구글 스프레드시트의 ID를 여기에 입력하세요.
spreadsheet_id = "1rRBAZomfN2pU9mp9y7hwrkyFpHGnyWvGb3-aViXIpbM"
